name: flaxum_fileshare
description: "Fileshare web client."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dropzone: ^4.2.0
  flutter_graph_view: ^1.1.4
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  json_annotation: ^4.9.0
  loading_animation_widget: ^1.3.0
  logger: ^2.5.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  provider: ^6.1.2
  flutter_svg: ^2.0.16
  gestures: ^1.0.0
  file_picker: ^8.1.6
  universal_html: ^2.2.4
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - assets/
