// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `Coordinate`, `Object`

BigInt rsPointOnCircle({required Circle circle, required int number}) =>
    RustLib.instance.api
        .crateApiSimpleRsPointOnCircle(circle: circle, number: number);

class Circle {
  final double x;
  final double y;
  final double r;

  const Circle({
    required this.x,
    required this.y,
    required this.r,
  });

  @override
  int get hashCode => x.hashCode ^ y.hashCode ^ r.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Circle &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          r == other.r;
}
